codecov:
  bot: mcgain
coverage:
  status:
    project: off
    patch:
      default:
        against: parent
        target: 80%
        branches: null
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: error
        only_pulls: true
comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
