name: argo-admin

type: node

up:
  - git_hooks:
      commit-msg: ./scripts/commitlint.sh
      pre-commit: ./scripts/prettier.sh
  - railgun
  - node:
      version: v12.11.1
      yarn: true
      packages:
        - .

commands:
  build: yarn run build
  console: node
  new-component: node ./scripts/new-component
  new-extension-point: node ./scripts/new-extension-point
  new-extension-api: node ./scripts/new-extension-api
  nuke: yarn run clean && rm -rf ./node_modules
  server: yarn run server --host=https://argo-playground.myshopify.io
  simulator: yarn run simulator
  test: yarn run test
  build-consumer: yarnpkg build && ./scripts/build-consumer.sh
  restore-consumer: ./scripts/restore-consumer.sh
  clean: git clean -xdf ./packages

open:
  app: https://argo-playground.myshopify.io
