api_version = "2023-10"

[[extensions]]
type = "ui_extension"
name = "My Extension"
handle = "my-extension"

[[extensions.targeting]]
module = "./src/index.ts"
target = "purchase.checkout.block.render"

[[extensions.metafields]]
namespace = "my_namespace"
key = "my_key"

[extensions.settings]
[[extensions.settings.fields]]
key = "banner_title"
type = "single_line_text_field"
name = "Banner title"
description = "Enter a title for the banner"
