type = "checkout_ui_extension"
name = "My Extension"

extension_points = ['Checkout::Dynamic::Render']

[[metafields]]
namespace = "my_namespace"
key = "my_key"

[settings]
[[settings.fields]]
key = "banner_title"
type = "single_line_text_field"
name = "Banner title"
description = "Enter a title for the banner"
