# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
type = "ui_extension"
name = "loyalty-extension"

handle = "loyalty-extension"
description = "Loyalty Points Extension"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/LoyaltyPointsBlock.tsx"
target = "pos.customer-details.block.render"

