api_version = "2023-07"

[[extensions]]
name = "My checkout extension"
handle = "checkout-ui"
type = "ui_extension"

  [[extensions.metafields]]
  namespace = "my-namespace"
  key = "my-key"
  [[extensions.metafields]]
  namespace = "my-namespace"
  key = "my-other-key"

  [extensions.capabilities]
  network_access = true
  block_progress = true
  api_access = true

  [extensions.settings]
    [[extensions.settings.fields]]
    key = "field_key"
    type = "boolean"
    name = "field-name"
    [[settings.fields]]
    key = "field_key_2"
    type = "number_integer"
    name = "field-name-2"

  [[extensions.targeting]]
  target = "purchase.checkout.block.render"
  module = "./CheckoutDynamicRender.jsx"

