name: Create Stable Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New stable version (YYYY-MM)'
        required: true
        type: string

jobs:
  create-stable-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Create new branch
        run: |
          git checkout -b ${{ github.event.inputs.version }} origin/unstable
          git push -u origin ${{ github.event.inputs.version }}

      - name: Create branch protection rule
        uses: octokit/request-action@v2.x
        with:
          route: PUT /repos/{owner}/{repo}/branches/{branch}/protection
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          branch: ${{ github.event.inputs.version }}
          required_status_checks: '{"strict": true, "contexts": []}'
          enforce_admins: 'true'
          required_pull_request_reviews: '{"required_approving_review_count": 1}'
          restrictions: 'null'
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - name: Update LATEST_STABLE_VERSION
        uses: octokit/request-action@v2.x
        with:
          route: PATCH /repos/{owner}/{repo}/actions/variables/LATEST_STABLE_VERSION
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          name: LATEST_STABLE_VERSION
          value: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
