name: Deploy

on:
  push:
    branches:
      - 2023-04
      - 2023-07

env:
  DIST_TAG: ${{ github.ref_name == '2023-07' && 'latest' || github.ref_name }}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare

      - id: changesets
        name: Create release Pull Request or publish to NPM
        uses: changesets/action@v1
        with:
          title: Version Packages (${{ github.ref_name }})
          publish: yarn run deploy --tag $DIST_TAG
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
