name: Deploy

on:
  push:
    branches:
      - 2022-10
      - 2023-01

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Changesets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare

      - id: changesets
        name: Create release Pull Request or publish to NPM
        uses: changesets/action@v1
        with:
          title: Version Packages (${{ github.ref_name }})
          publish: yarn run build && yarn run deploy --tag ${{ github.ref_name }}
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
