name: Deploy

on:
  push:
    branches:
      - jkv/keep-generated-docs
    paths:
      - 'packages/ui-extensions/**'
      - 'packages/ui-extensions-react/**'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  changesets:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare

      - name: Build checkout docs
        run: yarn docs:checkout un-versioned ./docs/surfaces/checkout/temp

      - name: Compare checkout docs
        run: yarn compare-docs --output packages/ui-extensions/docs/surfaces/checkout/generated
