name: Unstable Snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - unstable

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unstable-snapshot:
    name: Unstable Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/actions/prepare
      - name: Deploy snapshot versions
        run: yarn run deploy:unstable
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
