name: Remote DOM Unstable Snapshot

on:
  workflow_dispatch:
  push:
    branches:
      - remote-dom

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  unstable-snapshot:
    name: Remote DOM Unstable Snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}

      - uses: ./.github/workflows/actions/prepare

      - name: Create an .npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cat << EOF > "$HOME/.npmrc"
            //registry.npmjs.org/:_authToken=$NPM_TOKEN
          EOF

      - name: Deploy snapshot versions
        run: yarn run deploy:unstable
        env:
          GITHUB_TOKEN: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
